  <section class="container1">
      <article>

          <h1 class="h1">Actualité</h1>
          <div class="center">
              <img src="public/images/president.jpg" alt="président du TC thonon">
          </div>
          <h3>Le nouveau président du tennis club se lance dans une opération séduction</h3>

          <p>Le tennis squash club de Thonon-les-Bains a son nouveau président. Gérard Bastian a dressé les quelques grands axes autour desquels il compte tirer l’association sportive vers le haut. Il veut, entre autres, donner aux néophytes l’envie
              de s’initier aux sports de raquette. Fraîchement retraité, Gérard Bastian a pris les manettes du tennis club de Thonon. Réputé pour sa pugnacité, cet ancien fana de boxe, tombé amoureux de la balle jaune, a des idées plein la tête.
              Et il le fait savoir.</p>
          <p class="actu1">
              <strong>A l’occasion de votre assemblée générale, la mairie s’est engagée à investir 180 000 euros pour le club. Dans quel but ?</strong>
          </p>
          <p> Afin de mener à bien la réfection de deux courts en terre battue. Cette somme comprendrait
              également l’amélioration des éclairages et des accès aux terrains intérieurs. On nous dit souvent que l’on dispose d’installations exceptionnelles, ce qui est vrai. Mais elles sont un peu vieillissantes. Certaines terres battues
              sont très usées et nos courts extérieurs en dur commencent à se fissurer.
          </p>
          <p class="actu1">
              <strong>Vous disposez d’un court de padel (un nouveau sport de raquette qui mélange squash et tennis). La création d’un deuxième terrain est-elle envisagée ?</strong>
          </p>
          <p> La mairie ne nous a rien promis à ce sujet. Mais le padel, j’y crois très fort. Je suis persuadé que la pratique va se développer. C’est hyper ludique, on s’amuse rapidement, plus vite qu’avec le tennis. Et pour promouvoir notre activité, on va la faire
              tester à d’autres clubs sportifs. Je pense au rugby par exemple. C’est un excellent moyen de travailler les appuis. L’idée, c’est aussi d’aller à la rencontre des comités d’entreprise, de les encourager à venir passer un moment
              ensemble en dehors du travail, sur notre court de padel. La création d’un deuxième terrain finira, à terme, par être franchement envisageable.
          </p>
          <p class="actu1">
              <strong>Quel coût cela représenterait-il ?</strong>
          </p>
          <p> Selon la fédération, on pourrait en construire un pour environ 25 000 euros. Comment faire face au déclin de la pratique du tennis ? Le nombre de licenciés chute en France… De notre
              côté, sur ces dernières années, on constate une augmentation des licenciés toutes catégories confondues (450 adhérents en moyenne). Nos cours adultes tournent très bien. Mais, je pense qu’on peut attirer encore plus de monde. Et
              pour cela, je compte m’appuyer sur nos coaches qui ont d’excellentes idées. A titre personnel, je réfléchissais à un éventuel développement du club house. Avant, il était en gérance. Ce ne serait pas une mauvaise chose qu’il le
              redevienne. Disposer d’un service de restauration pourrait être l’occasion d’attirer les jeunes des lycées alentours ou d’autres sportifs. Ils découvriraient dans le même temps notre club et ses activités. Après je ne ferai évidemment
              rien seul, tout cela doit être l’objet de discussions.
          </p>
          <p>Interview réalisée en Février 2020</p>
      </article>
  </section>
  <div class="btn">
      <i class="fas fa-arrow-circle-up"></i>
  </div>

  <script src="public/js/scroll.js"></script>