<section class="adhesion">
    <div id="infoAdhesion">
        <h3>Infos</h3>
        <p>Toute demande de licence doit être accompagnée d'un certificat médical d'aptitude à l'activité physique de moins de trois mois.</p>
        <p> Les demandes ne remplissant pas cette condition ne pourront pas être transmises à la Fédération Française de Tennis, entrainant donc la non-délivrance de la licence.</p>
    </div>
    <div class="center" id="tarifs">
        <h3>Tarifs 2020-2021</h3>


        <table>

            <thead>
                <tr>
                    <th></th>
                    <th>Formule complète</th>
                    <th>Formule extérieurs</th>
                    <th>Formule hiver</th>
                    <th>Formule été</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td></td>
                </tr>
                <tr>
                    <td></td>
                    <td>licence
                        + courts couverts
                        + courts extérieurs
                        + padel
                        + 4 invitations</td>
                    <td>licence
                        + courts extérieurs
                        + padel
                        + 4 invitations
                    </td>
                    <td>licence
                        + courts couverts
                        + courts extérieurs
                        + padel
                        + 1 invitation
                    </td>
                    <td>licence
                        + courts extérieurs
                        + padel
                    </td>
                </tr>
                <tr>
                    <td>Adultes</td>
                    <td>235 eur</td>
                    <td>175 eur</td>
                    <td>200 eur</td>
                    <td>110 eur</td>
                </tr>
                <tr>
                    <td>Couples</td>
                    <td>380 eur</td>
                    <td>260 eur</td>
                    <td>340 eur</td>
                    <td>110 eur</td>
                </tr>
                <tr>
                    <td>Jeunes -18</td>
                    <td>145 eur</td>
                    <td>115 eur</td>
                    <td>115 eur</td>
                    <td>110 eur</td>
                </tr>
                <tr>
                    <td>Etudiants</td>
                    <td>185 eur</td>
                    <td>185 eur</td>
                    <td>155 eur</td>
                    <td>110 eur</td>
                </tr>
            </tbody>
        </table>

    </div>
</section>
<div class="btn">
    <i class="fas fa-arrow-circle-up"></i>
</div>


<!--- Fichier JS --->

<script src="public/js/scroll.js"></script>