<!--- utilisation d'un tableau pour la présentation du form d'identification --->
<div id="center">
    <?php
    if (isset($_SESSION["confirmation"])) {
    ?>
        <div class="alerte-confirmation">
            <?php echo $_SESSION["confirmation"]; ?>
        </div>
    <?php } ?>
    <h2>Connexion</h2>


    <form id="form-connexion" method="POST" action="index.php">

        <table class="tabconx" align="center">
            <tr>
                <td align="right">
                    <label for="mailconnect">Mail :</label>
                </td>
                <td>
                    <input class="mailconx" type="text" required placeholder="Votre mail" name="mailconnect" />
                </td>
            </tr>
            <tr>
                <td align="right">
                    <label for="mdpconnect">Mot de passe :</label>
                </td>
                <td>
                    <input class="passwordconx" type="password" required placeholder="Votre mot de passe" name="mdpconnect" />
                </td>
            </tr>
            <tr>

                <td align="center" colspan="2">

                    <input class="inputconx" type="submit" name="formconnexion" value="Connexion" />

                </td>
            </tr>
        </table>
        <input type="hidden" name="login" value="connexion" />
    </form>
    <div id="connectionP">
        <p>Si vous avez déjà créé un compte sur notre blog veuillez vous connecter afin d'accéder aux fonctions du blog et en profiter pleinement, sinon veuillez vous inscrire.</p>
    </div>
    <?php
    /* insertion des messages d'erreurs si le formulaire est mal rempli */
    if (isset($erreur)) {
        echo '<font color="red">' . $erreur . "</font>";
    }
    ?>
</div>
</section>
<div class="btn">
    <i class="fas fa-arrow-circle-up"></i>
</div>

<?php
if (isset($_SESSION["confirmation"]))
    unset($_SESSION["confirmation"]);
?>

<!--- Fichier JS --->

<script src="public/js/scroll.js"></script>
<script src="public/js/timeout.js"></script>