<section class="contacter">
    <div id="coordonnees">

        <p>Le tennis club de THONON-LES-BAINS se fera un plaisir de répondre à toutes vos questions concernant le tennis, le squash et le padel.</p>
        <p>Pour cela 2 solutions: le contact "à distance", ou bien le contact "présentiel" en venant nous rejoindre sur le site de nos infrastructures.</p>
        <h3>Nous contacter</h3>
        <h4>Jours et horaires d'ouverture</h4>
        <p>Lundi: fermé</p>
        <p>Mardi: 17h à 20h</p>
        <p>Mercredi: 9h à 20h</p>
        <p>Jeudi et Vendredi: 10h à 12h et 17h à 20h</p>
        <p>Samedi: 9h à 18h</p>
        <p>Dimanche: 10h à 13h30</p>

        <h4>Coordonées</h4>

        <ul>
            <li>Adresse: Avenue de la Grangette 74200 Thonon-les-bains</li>
            <li>Tél: 04 50 71 69 51</li>
            <li>Mail: clement.faivre8@wanadoo.fr</li>
        </ul>
    </div>
    <div id="localisation">
        <h3>Nous localiser</h3>
        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d5506.201641130886!2d6.484187691317026!3d46.367387657145535!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x478c3e897106ff93%3A0x408ab2ae4ba9680!2s74200%20Thonon-les-Bains!5e0!3m2!1sfr!2sfr!4v1573553812695!5m2!1sfr!2sfr" width="100%" height="450" frameborder="0" style="border:0;" allowfullscreen=""></iframe>
    </div>


</section>
<div class="btn">
    <i class="fas fa-arrow-circle-up"></i>
</div>


<!--- Fichier JS --->

<script src="public/js/scroll.js"></script>