    <div id="description">
        <p>L'école de tennis du TC THONON propose de nombreux cours s'adressant aux enfants, bien sûr, mais aussi aux adultes. Ces cours peuvent être individuels ou en groupe ("à la carte"), ou bien dispensés dans le cadre des cours de l'école de tennis qui ont lieu le mercredi ou le samedi en fonction de vos souhaits et des places disponibles.
            Tous nos cours sont dispensés par nos 2 professeurs Thierry et Anthony, tous 2 diplômés d'état et professeurs au sein de notre club depuis plus d'une décénie.</p>
    </div>

    <!----- présentation en carte survol------>
    <div class="body-prof">
        <div class="container-prof">
            <div class="article">
                <div class="article-image">
                    <img src="public/images/thierry.jpg" alt="thierry professeur TC thonon">
                </div>
                <div class="article-content">
                    <p class="thierry">CASTREC Thierry</p>
                    <p class="cv-thierry">Meilleur classement 4/6</p>
                    <p>BE1 Tennis obtenu en 1998</p>
                    <p>Moniteur au Tennis Club de Thonon les Bains depuis 2005</p>
                    <p>Responsable centre d'entrainement</p>
                    <p>Entraineur Equipe 1 Dames</p>
                    <p>Tél: 06 15 20 36 42</p>
                </div>
            </div>
            <div class="article">
                <div class="article-image">
                    <img src="public/images/anthony.jpg" alt="anthony professeur TC thonon">
                </div>
                <div class="article-content">

                    <p class="anthony">MERLIN Anthony</p>
                    <p class="cv-anthony">
                    <p>Meilleur classement 4/6</p>
                    <p>DESJEPS Tennis obtenu en 2015</p>
                    <p>Licence STAPS Entrainement obtenue en 2009</p>
                    <p> Moniteur au Tennis Club de Thonon les Bains depuis 2010</p>
                    <p> Responsable du Mini Tennis</p>
                    <p> Entraineur Equipes 1 et 2 Hommes</p>
                    <p> Tél: 06 15 20 38 41</p>
                </div>
            </div>
        </div>
    </div>
    <div class="btn">
        <i class="fas fa-arrow-circle-up"></i>
    </div>


    <!--- Fichier JS --->

    <script src="public/js/scroll.js"></script>