<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="http://localhost/tennis.com/public/css/projet1.css" type="text/css">
    <title>Erreur 404</title>
    <style>

    </style>
</head>

<body>
    <div class="erreur">
        ERREUR 404
        <a class="retour" href="http://localhost/tennis.com/index.php?page=home">Aller à la page d'acceuil</a>
    </div>



</body>

</html>