<div class="accueil">

   <h1 class="h1">Bienvenue</h1>



   <div class="slider-container">
      <div class="effect slide">
         <img src="public/images/infrastructure01.jpg" alt="cours tennis thonon">
      </div>
      <div class="effect slide">
         <img src="public/images/padel.jpg" alt="terrain de padel thonon">
      </div>
      <div class="effect slide">
         <img src="public/images/terre-battue01.jpg" alt="cours terre battue">
      </div>
   </div>

   <div class="dot-container">
      <span></span>
      <span></span>
      <span></span>
   </div>
   <div class="texteAccueil">
      <p>Le club tennis de THONON-LES-BAINS est heureux de vous accueillir sur sont site où vous trouverez toutes les informations relevant de la vie du club et bien sûr les modalités visant à nous rejoindre pour un match, une saison ou une carrière.</p>
      <p>Il vous suffira donc d'un clic pour nous contacter ou bien nous géolocaliser afin de venir nous rencontrer, faire une partie, assister aux matchs et supporter nos équipes ou tout simplement profiter de notre snack dans un esprit convivial et un décors de rêve.</p>
   </div>
   <div class="btn">
      <i class="fas fa-arrow-circle-up"></i>
   </div>
</div>
<script src="public/js/slider-accueil.js"></script>
<script src="public/js/scroll.js"></script>