<section class="presentation">

    <h1 class="h1">Organigramme</h1>

    <p>Une équipe toujours prête à vous aider dans la joie et la bonne humeur, mais toujours avec rigueur et sérieux.</p>
    <div id="bouton" onclick="javascript:viewImage('image');"> Afficher l'organigramme </div>
    <div id="image" class="present-img"></div>

</section>


<script src="public/js/organigramme.js"></script>



<h1 class="h1">Infrastructures</h1>


<div class="sliderP-container">
    <div class="effect slideP">
        <img src="public/images/entree.jpg" alt="entrée TC thonon">
        <p class="caption">Bienvenue</p>
    </div>
    <div class="effect slideP">
        <img src="public/images/infrastructure01.jpg" alt="cours TC thonon">
        <p class="caption">Vue aérienne</p>
    </div>
    <div class="effect slideP">
        <img src="public/images/terre-battue.jpg" alt="court en terre battue">
        <p class="caption">Court terre battue</p>
    </div>
    <div class="effect slideP">
        <img src="public/images/terre-battue01.jpg" alt="court en terre à thonon ">
        <p class="caption">Court en terre battue</p>
    </div>
    <div class="effect slideP">
        <img src="public/images/terre-et-bulle.jpg" alt="vue terrain et bulle">
        <p class="caption">Terre et bulle</p>
    </div>
    <div class="effect slideP">
        <img src="public/images/score.jpg" alt="tableau score thonon">
        <p class="caption">Tableau de score</p>
    </div>
    <div class="effect slideP">
        <img src="public/images/terrain-et-bulle.jpg" alt="vue terrain et bulle">
        <p class="caption">Terrain et bulle</p>
    </div>
    <div class="effect slideP">
        <img src="public/images/ciment01.jpg" alt="terrain en ciment">
        <p class="caption">Court extérieur</p>
    </div>
    <div class="effect slideP">
        <img src="public/images/ciment02.jpg" alt="court exterieur ciemnt">
        <p class="caption">Court ciment</p>
    </div>
    <div class="effect slideP">
        <img src="public/images/padel-s1.jpg" alt="court padel">
        <p class="caption">Padel</p>
    </div>
    <div class="effect slideP">
        <img src="public/images/padel-s2.jpg" alt="court padel">
        <p class="caption">Padel</p>
    </div>
    <div class="effect slideP">
        <img src="public/images/padel-s3.jpg" alt="court padel">
        <p class="caption">Padel</p>
    </div>
    <div class="effect slideP">
        <img src="public/images/padel-s4.jpg" alt="court padel">
        <p class="caption">Padel</p>
    </div>
    <div class="effect slideP">
        <img src="public/images/padel.jpg" alt="court padel">
        <p class="caption">Padel</p>
    </div>
    <div class="effect slideP">
        <img src="public/images/bulle.jpg" alt="bulle TC thonon">
        <p class="caption">A l'abris dans la bulle</p>
    </div>
    <div class="effect slideP">
        <img src="public/images/tennis-et-montagne.jpg" alt="tennis à la montagne">
        <p class="caption">Sport et montagne</p>
    </div>
    <div class="effect slideP">
        <img src="public/images/squash.jpg" alt="squash TC thonon">
        <p class="caption">Terrain de squash</p>
    </div>
    <div class="effect slideP">
        <img src="public/images/bureau.jpg" alt="bureau du TC thonon">
        <p class="caption">Le bureau</p>
    </div>
    <div class="effect slideP">
        <img src="public/images/snack.jpg" alt="snack TC thonon">
        <p class="caption">Le snack</p>
    </div>
</div>

<div class="btn">
    <i class="fas fa-arrow-circle-up"></i>
</div>


<!--- Fichier JS --->
<script src="public/js/sliderP.js"></script>
<script src="public/js/scroll.js"></script>